@startuml
Main -> ProgramControl: runProgram()
ProgramControl --> ProgramControl: readFromFile()
ProgramControl -> StartMenu: runStartMenu()
StartMenu --> StartMenu: createNewUser()
StartMenu --> StartMenu: login()
StartMenu -> ProgramControl: setCurrentUser()
ProgramControl -> MainMenu: runMainMenu()
ProgramControl <-> MainMenu: getAllMedia()
MainMenu --> MainMenu: suggestedMedia()
MainMenu --> MainMenu: searchEngine()
MainMenu -> AMedia: playMedia()
AMedia -> User: addWatchedMedia()
User --> User: removeSavedMedia()
User -> MainMenu: runMainMenu()
MainMenu --> MainMenu: suggestedMedia()
MainMenu --> MainMenu: searchEngine()
MainMenu -> User:addSavedMedia()
User -> MainMenu: runMainMenu()
MainMenu --> MainMenu: logOut()
MainMenu -> ProgramControl: writeToFile()
@enduml