@startuml
class Main
Main <|-- ProgramControl
ProgramControl *-- StartMenu
ProgramControl *-- MainMenu
ProgramControl *-- User
ProgramControl *-- DataHandling
DataHandling *-- FileHandling
DataHandling *-- DatabaseHandling
MainMenu *-- Search
Search *-- AMedia
AMedia <|-- Movie
AMedia <|-- Series

interface DataHandling{
+ ArrayList<AMedia> readFromMovieFile(String path)
+ ArrayList<AMedia> readFromSeriesFile(String path)
+ ArrayList<User> readFromUserFile(String path, ArrayList<AMedia> allMedia)
+ void writeToUserFile(String path, ArrayList<User> allUsers)
+ ArrayList<String> readFromCategoryFile(String path)
}

class DatabaseHandling{
+ Connection connection
- String url
- String username
- String password
+ boolean isDatabaseOnline

+ void closeConnection()
- void establishConnection()
+ ArrayList<AMedia> readMovieData(String path)
+ ArrayList<AMedia> readSeriesData(String path)
+ ArrayList<User> readUserData(String path, ArrayList<AMedia> allMedia)
+ void writeUserData(String path, ArrayList<User> allUsers)
+ ArrayList<String> readCategoryData(String path)
+ void addSavedMovie(AMedia media)
+ void addSavedSeries(AMedia media)
+ void removeSavedMovie(AMedia media)
+ void removeSavedSeries(AMedia media)
+ void addWatchedMovie(AMedia media)
+ void addWatchedSeries(AMedia media)
- int findMovieID(AMedia media)
- int findSeriesID(AMedia media)
- int findUserID()
}
class Search{
- Scanner scanner
- ArrayList<AMedia> allMovies
- ArrayList<AMedia> allSeries
- ArrayList<String> allCategories
+ Search(ArrayList<AMedia> allMovies, ArrayList<AMedia> allSeries, ArrayList<String> allCategories)
+ void searchEngine()
- AMedia searchMovies(ArrayList<AMedia> allMovies)
- AMedia searchSeries(ArrayList<AMedia> allSeries)
- void searchByMediaName(ArrayList<AMedia> listOfMedia)
- void searchByCategory(ArrayList<AMedia> listOfMedia, ArrayList<String> allCategories)
- void searchByChosenCategory(String chosenCategory, ArrayList<AMedia> listOfMedia)
- void searchByRating(ArrayList<AMedia> media)
- void searchByYear(ArrayList<AMedia> media)
+ void searchBySavedMedia()
+ void searchByWatchedMedia()
}
class ProgramControl{
- ArrayList<User> allUsers
- ArrayList<AMedia> allMedia
+ static User currentUser
+ static MainMenu mainMenu
+ static DataHandling dataHandling
+ static boolean usingDatabase
+ void runProgram()
}

class StartMenu{
- ArrayList<User> allUsers
- Scanner scanner
+ StartMenu(ArrayList<User> allUsers)
+ User runStartMenu()
- User login()
- User createNewUser()
}

class MainMenu{
- Search search
- ArrayList<User> allUsers
- ArrayList<AMedia> allMovies
- ArrayList<AMedia> allSeries
- ArrayList<String> allCategories
- Random rnd
- Scanner scanner
+ MainMenu(ArrayList<User> allUsers, ArrayList<AMedia> allMovies, ArrayList<AMedia> allSeries)
+ void runMainMenu()
- void suggestedMedia()
- AMedia getRandomMediaFromCategory(String category, ArrayList<AMedia> allMoviesAltered)
- String getRandomCategory(String[] lastPlayedCategories)
- void logOut()
- void userOptions()
}

abstract class AMedia{
  Scanner sc
# String name
# String category
# float rating
# int releaseYear
  AMedia(String name, String category, float rating, int releaseYear)
+ String getName()
+ String getCategory()
+ float getRating()
+ int getReleaseYear()
# {abstract} void playMedia(AMedia media)
+ void chooseMedia()
}

class Movie{
+ Movie (String name, String category, float rating, int releaseYear)
+ void playMedia()
}

class Series{
- int season
- int episode
- int endYear
+ Series (String name, String category, float rating, int releaseYear, int season, int episode, int endYear)
+ String getDatabaseName()
+ int getEpisode()
+ int getSeason()
+ int getEndYear()
+ void playMedia()
}

class User{
- String userName
- String password
- int age
- ArrayList<AMedia> watchedMedia
- ArrayList<AMedia> savedMedia
+ User(String userName, String password, int age, ArrayList<AMedia>(), ArrayList<AMedia>())
+ String getUsername()
+ void setUsername()
+ String getPassword()
+ void setPassword()
+ int getAge()
+ ArrayList<AMedia> getWatchedMedia()
+ ArrayList<AMedia> getSavedMedia()
+ void addSavedMedia(AMedia)
+ void removeSavedMedia(AMedia)
+ void addWatchedMedia(AMedia)
}

class FileHandling{
+ ArrayList<AMedia> readMovieData(String path)
+ ArrayList<AMedia> readSeriesData(String path)
+ ArrayList<User> readUserData(String path, ArrayList<AMedia> allMedia)
+ void writeUserData(String path, ArrayList<User> allUsers)
+ ArrayList<String> readCategoryData(String path)
}

@enduml