@startuml
class Main
Main *-- FileHandling
FileHandling <|-- ProgramControl
ProgramControl *-- StartMenu
ProgramControl *-- MainMenu
ProgramControl *-- User

MainMenu *-- AMedia
AMedia <|-- Movie
AMedia <|-- Series

class ProgramControl{
+ ArrayList<User> allUsers
+ ArrayList<AMedia> allMedia
+ static User currentUser
+ static Scanner userInput
+ runProgram()
+ getCurrentUser()
+ setCurrentUser(User user)
+ getAllMedia()
}

class StartMenu{
+ StartMenu(ArrayList<User> allUsers)
+ runStartMenu()
- login()
- createNewUser()
}

class MainMenu{
+ MainMenu(ArrayList<AMedia> allMedia)
+ runMainMenu()
- suggestedMedia()
- searchEngine()
- logOut()
}

abstract class AMedia{
- String name
- String category
- float rating
- int releaseYear
+ AMedia(String name, String category, float rating, int releaseYear)
+ abstract playMedia()
}

class Movie{
+ Movie (String name, String category, float rating, int releaseYear)
}

class Series{
- int season
- int episode
+ Series (String name, String category, float rating, int releaseYear, int season, int episode)
}

class User{
- String userName
- String password
- int age
- ArrayList<AMedia> watchedMedia
- ArrayList<AMedia> savedMedia
+ User(String userName, String password, int age)
+ getWatchedMedia()
+ getSavedMedia()
+ addSavedMedia(AMedia)
+ removeSavedMedia(AMedia)
+ addWatchedMedia(AMedia)
}

interface FileHandling{
+ readFromFile()
+ writeToFile()
}

@enduml